### ISSUE TITLE
What's new info for 16

### ISSUE THREAD

**Issue by blizzz** [nextcloud/changelog_server#14]
@jospoortvliet RC might be already be a good time to get it in, anyhow best some time before final to get transations in

**Comment by jospoortvliet** [comment]
# whatsnew sysadmins
* Machine-learning powered suspicious login detection
* Access Control Lists in Groupfolders
* Variables for external storage (LDAP has '$HOME')

# whatsnew users
* Smart recommendations for files, sharees
* Projects: group files, chats, tasks for easy finding
* right-click in Files, new document viewer & more

What do you think, OK?

**Comment by blizzz** [comment]
fine with me
