### ISSUE TITLE
hook into transifex

### ISSUE THREAD

**Issue by blizzz** [nextcloud/changelog_server#2]
contributes to  #1 
* [x] requires schema file from #1 

The whats new files reside in `/data/` and are named x.y.z.xml, according to the version. As of creating the issue we dont have a production file yet, a test file resides in https://github.com/nextcloud/changelog_server/blob/master/tests/data/13.0.0.xml

To translate is the content wihtin the `<whatsNew lang="en">`  tag.  The tranlsations should be placed as seperate `<whatsNew>` element in  the same file, with the accoriding `lang` attribute.

**Comment by blizzz** [comment]
@MorrisJobke how's the outlook?

**Comment by MorrisJobke** [comment]
Good question .... let me think about this.

**Comment by MorrisJobke** [comment]
https://www.transifex.com/nextcloud/nextcloud/changelog_server/ - it's pushed to transifex at least. :)

**Comment by MorrisJobke** [comment]
b167248ec69e88a6acc0944cfdc5b401e5b1b45c
618c36971336ac2f0467ad8a7d07727e88cb9f7d

**Comment by blizzz** [comment]
Awesome, thank you @MorrisJobke  🚀🚀🚀
