### ISSUE TITLE
14.0.0 changes review

### ISSUE THREAD

**Issue by blizzz** [nextcloud/changelog_server#6]
@jospoortvliet seems the 100 characters/line are a bit optimistic. Perhaps we can trim it down?  Will only be visible when RC 1 is out anyway. You can edit this file https://github.com/nextcloud/changelog_server/blob/master/data/14.0.0.xml

![screenshot_20180816_134907](https://user-images.githubusercontent.com/2184312/44206774-259de200-a15b-11e8-875b-221974ad39d0.png)

![screenshot_20180816_135031](https://user-images.githubusercontent.com/2184312/44206824-5847da80-a15b-11e8-8d7f-7ed14b77bdac.png)

**Comment by jospoortvliet** [comment]
see https://github.com/nextcloud/changelog_server/pull/7
